# Generated by Django 3.1.1 on 2020-09-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwords',
            options={'verbose_name_plural': 'passwords'},
        ),
    ]
